---
- name: Update and upgrade packages
  hosts: all
  become: yes
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        #update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_os_family == "Debian"
